/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_jqorz_jni_JniGet */

#ifndef _Included_com_jqorz_jni_JniGet
#define _Included_com_jqorz_jni_JniGet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jqorz_jni_JniGet
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jqorz_jni_JniGet_getHello
  (JNIEnv *env, jclass){
  std::string hello = "1112";
  return (*env).NewStringUTF(hello.c_str());
  }

#ifdef __cplusplus
}
#endif
#endif